sudo: false
language: elixir
services:
  - rabbitmq
elixir:
  - 1.4.5
  - 1.5.2
  - 1.5.3
otp_release:
  - 19
  - 20.1
  - 20.2
script: MIX_ENV=test mix compile --warnings-as-errors && MIX_ENV=test mix test && integration_test/run
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
